name = "zo-api-gateway"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_NAMESPACE_ID"

# [vars]
# GATEWAY_KEY = "your-client-gateway-key"
# ADMIN_KEY = "your-admin-panel-key"
# COOLDOWN_MS = "60000"
